### ISSUE TITLE
cache issue

### ISSUE THREAD

**Issue by objmagic** [benley/bazel_rules_pex#11]
Hi, Ben

while you are working on Bazel's pex rules, I'm wondering if you have seen the following error message arising from pex:

````
    sys.exit(main())
  File "/home/travis/.cache/bazel/_bazel_travis/030a6cc9b27b34f2fe0e137b942f59bf/heron/bazel-out/local_linux-fastbuild/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/_pex.py", line 159, in main
    resolver_options_builder, interpreter=interpreter)
  File "/home/travis/.cache/bazel/_bazel_travis/030a6cc9b27b34f2fe0e137b942f59bf/heron/bazel-out/local_linux-fastbuild/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/bin/pex.py", line 472, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/home/travis/.cache/bazel/_bazel_travis/030a6cc9b27b34f2fe0e137b942f59bf/heron/bazel-out/local_linux-fastbuild/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/resolver.py", line 191, in resolve
    dist = self.build(package, resolvable.options)
  File "/home/travis/.cache/bazel/_bazel_travis/030a6cc9b27b34f2fe0e137b942f59bf/heron/bazel-out/local_linux-fastbuild/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/resolver.py", line 254, in build
    os.rename(target + '~', target)
OSError: [Errno 2] No such file or directory
````

I thought https://github.com/twitter/heron/pull/1052 should solve https://github.com/twitter/heron/issues/1051, but it didn't.

Any idea?

**Comment by benley** [comment]
Interesting - I don't think I have encountered that particular error yet.  Does it happen while building a particular package, or is it seemingly random?

**Comment by objmagic** [comment]
it's desperately random. Reading through some issues on pantsbuild/pex, I noticed some related issues (for example, https://github.com/pantsbuild/pex/pull/271). It seems that they relate to concurrency issues.

**Comment by benley** [comment]
I just saw this error for the first time!

```
ERROR: /Users/bstaffin/fb/provisioning/autograf/BUILD:18:1: null failed: pex_wrapper.pex failed: error executing command bazel-out/local-fastbuild/genfiles/external/io_bazel_rules_pex/pex/pex_wrapper.pex --find-links external/requests_wheel/file --pex-root .pex --entry-point autograf.editor --output-file ... (remaining 4 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 328, in execute
  File ".bootstrap/_pex/pex.py", line 260, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 292, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 371, in _execute
  File ".bootstrap/_pex/pex.py", line 429, in execute_entry
  File ".bootstrap/_pex/pex.py", line 434, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/bstaffin/.pex/install/pex_wrapper-0.0.0-py2-none-any.whl.d6351f1455dc968b0bc759fdfceb87ca14d267a9/pex_wrapper-0.0.0-py2-none-any.whl/pex_wrapper.py", line 123, in <module>
    main()
  File "/Users/bstaffin/.pex/install/pex_wrapper-0.0.0-py2-none-any.whl.d6351f1455dc968b0bc759fdfceb87ca14d267a9/pex_wrapper-0.0.0-py2-none-any.whl/pex_wrapper.py", line 87, in main
    resolver_options_builder)
  File "/Users/bstaffin/.pex/install/pex-1.1.13-py2.py3-none-any.whl.810ae2fd2aed30f981a3ffce9b81c2f374018f24/pex-1.1.13-py2.py3-none-any.whl/pex/bin/pex.py", line 489, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/Users/bstaffin/.pex/install/pex-1.1.13-py2.py3-none-any.whl.810ae2fd2aed30f981a3ffce9b81c2f374018f24/pex-1.1.13-py2.py3-none-any.whl/pex/resolver.py", line 200, in resolve
    dist = self.build(package, resolvable.options)
  File "/Users/bstaffin/.pex/install/pex-1.1.13-py2.py3-none-any.whl.810ae2fd2aed30f981a3ffce9b81c2f374018f24/pex-1.1.13-py2.py3-none-any.whl/pex/resolver.py", line 263, in build
    os.rename(target + '~', target)
OSError: [Errno 2] No such file or directory
```

I can't reproduce it, of course :-|
